name: GitHub actions - To Test Repo - Trigger Jenkins Job
run-name: Test Repo - Trigger Jenkins Job

on:
  push:
    branches: ["master"]

env:
  owner_name: ABhi
  TARGET_HOST: ${{ secrets.LAB_HOSTNAME }}
  TARGET_PORT: ${{ secrets.LAB_PORT }}
  TARGET_USERNAME: ${{ secrets.LAB_USERNAME }}
  TARGET_PASSWORD: ${{ secrets.LAB_PASSWORD }}

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Job Info
      run: echo "Job build_test is executing as part of new workflow - from $owner_name - with details $TARGET_HOST, $TARGET_PORT, $TARGET_USERNAME, $TARGET_PASSWORD"

    - name: Job 2
      run: echo 'Target port = $TARGET_PORT'
    # - uses: actions/checkout@v4
    # # - name: Set up JDK 17
    # #   uses: actions/setup-java@v4
    # #   with:
    # #     java-version: '17'
    # #     distribution: 'temurin'
    # #     cache: maven
    # - name: Setup Maven Action
    #   uses: s4u/setup-maven-action@v1.7.0
    #   with:
    #     checkout-fetch-depth: 0
    #     java-version: 17
    #     java-distribution: temurin
    #     maven-version: 3.9.8
    # - name: Test with Maven
    #   run: mvn -B test --file pom.xml

    - name: connect to LAb and trigger jenkins job
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest 
      with:
        host: '$TARGET_HOST'
        user: '$TARGET_USERNAME'
        pass: '$TARGET_PASSWORD'
        port: 42006
        connect_timeout: 10s 
        first_ssh: |
          sudo pwd
